// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Supermarket.Infrastructure.Persistence;

#nullable disable

namespace Supermarket.Infrastructure.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20260420084943_InitEmployeesAndScreenPermissions")]
    partial class InitEmployeesAndScreenPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Supermarket.Domain.Entities.AppScreen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ScreenKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ScreenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ScreenKey")
                        .IsUnique();

                    b.ToTable("APP_SCREENS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ScreenKey = "sales",
                            ScreenName = "Sales"
                        },
                        new
                        {
                            Id = 2,
                            ScreenKey = "products",
                            ScreenName = "Products"
                        },
                        new
                        {
                            Id = 3,
                            ScreenKey = "invoices",
                            ScreenName = "Invoices"
                        },
                        new
                        {
                            Id = 4,
                            ScreenKey = "offers",
                            ScreenName = "Offers"
                        },
                        new
                        {
                            Id = 5,
                            ScreenKey = "reports",
                            ScreenName = "Reports"
                        },
                        new
                        {
                            Id = 6,
                            ScreenKey = "inventory",
                            ScreenName = "Inventory"
                        },
                        new
                        {
                            Id = 7,
                            ScreenKey = "settings",
                            ScreenName = "Settings"
                        });
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("EMPLOYEES", (string)null);
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.EmployeeScreenPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("CanAccess")
                        .HasColumnType("bit");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<int>("ScreenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScreenId");

                    b.HasIndex("EmployeeId", "ScreenId")
                        .IsUnique();

                    b.ToTable("EMPLOYEE_SCREEN_PERMISSIONS", (string)null);
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.EmployeeScreenPermission", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Supermarket.Domain.Entities.AppScreen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Screen");
                });
#pragma warning restore 612, 618
        }
    }
}
